language: node_js
node_js:
  - 10
  - 12
  - 14
branches:
  only:
    - main
    - monorepo
install:
  - npm install
  - npx lerna bootstrap
script:
  - npm run build
  - npm run test:alt
  - npm run test
  # - npm run test:coverage:coveralls
