language: node_js
node_js:
  - 12
  - 14
branches:
  only:
    - main
install:
  - npm install
  - npx lerna bootstrap
script:
  - npm run build
  - npm run test:alt
  - npm run test
  - npm run docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main
